### ISSUE TITLE
Large numbers should be shown in a human friendly format

### ISSUE THREAD

**Issue by ernest-okot** [devinit/charts#3]
Examples: 
1000 -> 1k
1000000 -> 1m
1234000 -> 1.23m
![screenshot from 2017-06-12 13-44-44](https://user-images.githubusercontent.com/8332336/27030561-71a3abfa-4f75-11e7-8c1a-4eba4f06565b.png)
![screenshot from 2017-06-12 13-00-23](https://user-images.githubusercontent.com/8332336/27030562-71a96f68-4f75-11e7-81ce-2e072bc071e1.png)

**Comment by epicallan** [comment]
d3 has format function that does this well.
