### ISSUE TITLE
Line chart changes

### ISSUE THREAD

**Issue by ernest-okot** [devinit/charts#5]
- [ ] Add an option for smooth lines in line charts
![line](https://user-images.githubusercontent.com/8332336/27030925-c81ac094-4f76-11e7-82a7-8f20b7ce95b5.jpg)

**Comment by akmiller01** [comment]
Hey @ernest-okot , I don't think it's necessary to replicate the spline interpolation for line-charts. It's actually really misleading and can lead to really weird and impossible lines ([example](https://newtonexcelbach.wordpress.com/2010/05/06/using-cubic-splines-in-practice/)). Much more honest just to connect discrete data points with straight lines.

**Comment by ernest-okot** [comment]
Thanks Alex... i'll go ahead and close this to that effect
